spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yakirLE/scf-config-repository.git
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8888